---
- name: Verify
  hosts: all
  gather_facts: true

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ ansible_version }}"
          - "ansible_distribution => {{ ansible_facts['distribution'] }}"
          - "ansible_distribution_major_version => {{ ansible_facts['distribution_major_version'] }}"
          - "ansible_os_family  => {{ ansible_facts['os_family'] }}"
          - "ansible_system  => {{ ansible_facts['system'] }}"

    - name: Verify PBS Apt signing key exists
      ansible.builtin.stat:
        path: "/etc/apt/keyrings/proxmox-release-{{ ansible_facts['distribution_release'] }}.gpg"
      register: verify_apt_signing_key_status
      failed_when: not verify_apt_signing_key_status.stat.exists

    - name: Verify pbs-enterprise.list is absent (enterprise disabled by default)
      ansible.builtin.stat:
        path: '/etc/apt/sources.list.d/pbs-enterprise.list'
      register: verify_enterprise_repository_status
      failed_when: verify_enterprise_repository_status.stat.exists

    - name: Verify if pbs-no-subscription.list exists
      ansible.builtin.lineinfile:
        name: '/etc/apt/sources.list.d/pbs-no-subscription.list'
        line: 'deb [signed-by=/etc/apt/keyrings/proxmox-release-{{ ansible_facts["distribution_release"] }}.gpg] http://download.proxmox.com/debian/pbs {{ ansible_facts["distribution_release"] }} pbs-no-subscription'
        state: present
      check_mode: true
      register: verify_no_subscription_repository_status
      failed_when: (verify_no_subscription_repository_status is changed) or (verify_no_subscription_repository_status is failed)
